//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHQ.RD.WebServiceListener.UASV {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/CHQ.UA.WS")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UANodes", Namespace="http://schemas.datacontract.org/2004/07/CHQ.UA.WS")]
    [System.SerializableAttribute()]
    public partial class UANodes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrowseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrowsePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrowseName {
            get {
                return this.BrowseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrowseNameField, value) != true)) {
                    this.BrowseNameField = value;
                    this.RaisePropertyChanged("BrowseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrowsePath {
            get {
                return this.BrowsePathField;
            }
            set {
                if ((object.ReferenceEquals(this.BrowsePathField, value) != true)) {
                    this.BrowsePathField = value;
                    this.RaisePropertyChanged("BrowsePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverName {
            get {
                return this.DriverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverNameField, value) != true)) {
                    this.DriverNameField = value;
                    this.RaisePropertyChanged("DriverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverType {
            get {
                return this.DriverTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverTypeField, value) != true)) {
                    this.DriverTypeField = value;
                    this.RaisePropertyChanged("DriverType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeId {
            get {
                return this.NodeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeIdField, value) != true)) {
                    this.NodeIdField = value;
                    this.RaisePropertyChanged("NodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeType {
            get {
                return this.NodeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeTypeField, value) != true)) {
                    this.NodeTypeField = value;
                    this.RaisePropertyChanged("NodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceId {
            get {
                return this.SourceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIdField, value) != true)) {
                    this.SourceIdField = value;
                    this.RaisePropertyChanged("SourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueType {
            get {
                return this.ValueTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueTypeField, value) != true)) {
                    this.ValueTypeField = value;
                    this.RaisePropertyChanged("ValueType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UASubScription", Namespace="http://schemas.datacontract.org/2004/07/CHQ.DATACONTRACT.RD")]
    [System.SerializableAttribute()]
    public partial class UASubScription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeepAliveCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LifetimeCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNotificationsPerPublishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublishIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublishingEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KeepAliveCount {
            get {
                return this.KeepAliveCountField;
            }
            set {
                if ((this.KeepAliveCountField.Equals(value) != true)) {
                    this.KeepAliveCountField = value;
                    this.RaisePropertyChanged("KeepAliveCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LifetimeCount {
            get {
                return this.LifetimeCountField;
            }
            set {
                if ((this.LifetimeCountField.Equals(value) != true)) {
                    this.LifetimeCountField = value;
                    this.RaisePropertyChanged("LifetimeCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNotificationsPerPublish {
            get {
                return this.MaxNotificationsPerPublishField;
            }
            set {
                if ((this.MaxNotificationsPerPublishField.Equals(value) != true)) {
                    this.MaxNotificationsPerPublishField = value;
                    this.RaisePropertyChanged("MaxNotificationsPerPublish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublishInterval {
            get {
                return this.PublishIntervalField;
            }
            set {
                if ((this.PublishIntervalField.Equals(value) != true)) {
                    this.PublishIntervalField = value;
                    this.RaisePropertyChanged("PublishInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublishingEnabled {
            get {
                return this.PublishingEnabledField;
            }
            set {
                if ((this.PublishingEnabledField.Equals(value) != true)) {
                    this.PublishingEnabledField = value;
                    this.RaisePropertyChanged("PublishingEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubType {
            get {
                return this.SubTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTypeField, value) != true)) {
                    this.SubTypeField = value;
                    this.RaisePropertyChanged("SubType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UASubDetail", Namespace="http://schemas.datacontract.org/2004/07/CHQ.DATACONTRACT.RD")]
    [System.SerializableAttribute()]
    public partial class UASubDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UANodesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] UANodes {
            get {
                return this.UANodesField;
            }
            set {
                if ((object.ReferenceEquals(this.UANodesField, value) != true)) {
                    this.UANodesField = value;
                    this.RaisePropertyChanged("UANodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UADatabatchSetting", Namespace="http://schemas.datacontract.org/2004/07/CHQ.DATACONTRACT.RD")]
    [System.SerializableAttribute()]
    public partial class UADatabatchSetting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsEntireBatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeepTimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyNodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyNodeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RaiseAlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RunAdditionalEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaveConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SnapPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TriggerSnapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TriggerSnapValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TriggerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TriggerValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string memoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsEntireBatch {
            get {
                return this.IsEntireBatchField;
            }
            set {
                if ((this.IsEntireBatchField.Equals(value) != true)) {
                    this.IsEntireBatchField = value;
                    this.RaisePropertyChanged("IsEntireBatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KeepTimes {
            get {
                return this.KeepTimesField;
            }
            set {
                if ((this.KeepTimesField.Equals(value) != true)) {
                    this.KeepTimesField = value;
                    this.RaisePropertyChanged("KeepTimes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KeyNodeId {
            get {
                return this.KeyNodeIdField;
            }
            set {
                if ((this.KeyNodeIdField.Equals(value) != true)) {
                    this.KeyNodeIdField = value;
                    this.RaisePropertyChanged("KeyNodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyNodeName {
            get {
                return this.KeyNodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyNodeNameField, value) != true)) {
                    this.KeyNodeNameField = value;
                    this.RaisePropertyChanged("KeyNodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RaiseAlert {
            get {
                return this.RaiseAlertField;
            }
            set {
                if ((this.RaiseAlertField.Equals(value) != true)) {
                    this.RaiseAlertField = value;
                    this.RaisePropertyChanged("RaiseAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RunAdditionalEvent {
            get {
                return this.RunAdditionalEventField;
            }
            set {
                if ((this.RunAdditionalEventField.Equals(value) != true)) {
                    this.RunAdditionalEventField = value;
                    this.RaisePropertyChanged("RunAdditionalEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaveCondition {
            get {
                return this.SaveConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.SaveConditionField, value) != true)) {
                    this.SaveConditionField = value;
                    this.RaisePropertyChanged("SaveCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SnapPeriod {
            get {
                return this.SnapPeriodField;
            }
            set {
                if ((this.SnapPeriodField.Equals(value) != true)) {
                    this.SnapPeriodField = value;
                    this.RaisePropertyChanged("SnapPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubId {
            get {
                return this.SubIdField;
            }
            set {
                if ((this.SubIdField.Equals(value) != true)) {
                    this.SubIdField = value;
                    this.RaisePropertyChanged("SubId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TriggerSnap {
            get {
                return this.TriggerSnapField;
            }
            set {
                if ((object.ReferenceEquals(this.TriggerSnapField, value) != true)) {
                    this.TriggerSnapField = value;
                    this.RaisePropertyChanged("TriggerSnap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TriggerSnapValue {
            get {
                return this.TriggerSnapValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TriggerSnapValueField, value) != true)) {
                    this.TriggerSnapValueField = value;
                    this.RaisePropertyChanged("TriggerSnapValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TriggerType {
            get {
                return this.TriggerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TriggerTypeField, value) != true)) {
                    this.TriggerTypeField = value;
                    this.RaisePropertyChanged("TriggerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TriggerValue {
            get {
                return this.TriggerValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TriggerValueField, value) != true)) {
                    this.TriggerValueField = value;
                    this.RaisePropertyChanged("TriggerValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                if ((object.ReferenceEquals(this.memoField, value) != true)) {
                    this.memoField = value;
                    this.RaisePropertyChanged("memo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UAAlertType", Namespace="http://schemas.datacontract.org/2004/07/CHQ.DATACONTRACT.RD")]
    [System.SerializableAttribute()]
    public partial class UAAlertType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CanCancelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CanCancel {
            get {
                return this.CanCancelField;
            }
            set {
                if ((this.CanCancelField.Equals(value) != true)) {
                    this.CanCancelField = value;
                    this.RaisePropertyChanged("CanCancel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UASubView", Namespace="http://schemas.datacontract.org/2004/07/CHQ.DATACONTRACT.RD")]
    [System.SerializableAttribute()]
    public partial class UASubView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubscriptionidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Subscriptionid {
            get {
                return this.SubscriptionidField;
            }
            set {
                if ((this.SubscriptionidField.Equals(value) != true)) {
                    this.SubscriptionidField = value;
                    this.RaisePropertyChanged("Subscriptionid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UASubViewItem", Namespace="http://schemas.datacontract.org/2004/07/CHQ.DATACONTRACT.RD")]
    [System.SerializableAttribute()]
    public partial class UASubViewItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DecimalLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte RaiseAlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RangeMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RangeMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DecimalLength {
            get {
                return this.DecimalLengthField;
            }
            set {
                if ((this.DecimalLengthField.Equals(value) != true)) {
                    this.DecimalLengthField = value;
                    this.RaisePropertyChanged("DecimalLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte RaiseAlert {
            get {
                return this.RaiseAlertField;
            }
            set {
                if ((this.RaiseAlertField.Equals(value) != true)) {
                    this.RaiseAlertField = value;
                    this.RaisePropertyChanged("RaiseAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RangeMax {
            get {
                return this.RangeMaxField;
            }
            set {
                if ((this.RangeMaxField.Equals(value) != true)) {
                    this.RangeMaxField = value;
                    this.RaisePropertyChanged("RangeMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RangeMin {
            get {
                return this.RangeMinField;
            }
            set {
                if ((this.RangeMinField.Equals(value) != true)) {
                    this.RangeMinField = value;
                    this.RaisePropertyChanged("RangeMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UASV.IChqUASettings")]
    public interface IChqUASettings {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/GetData", ReplyAction="http://tempuri.org/IChqUASettings/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IChqUASettings/GetDataUsingDataContractResponse")]
        CHQ.RD.WebServiceListener.UASV.CompositeType GetDataUsingDataContract(CHQ.RD.WebServiceListener.UASV.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/saveUANodes", ReplyAction="http://tempuri.org/IChqUASettings/saveUANodesResponse")]
        int saveUANodes(CHQ.RD.WebServiceListener.UASV.UANodes node);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getUANodes", ReplyAction="http://tempuri.org/IChqUASettings/getUANodesResponse")]
        CHQ.RD.WebServiceListener.UASV.UANodes[] getUANodes(string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getUANode", ReplyAction="http://tempuri.org/IChqUASettings/getUANodeResponse")]
        CHQ.RD.WebServiceListener.UASV.UANodes getUANode(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getUANodeViaId", ReplyAction="http://tempuri.org/IChqUASettings/getUANodeViaIdResponse")]
        CHQ.RD.WebServiceListener.UASV.UANodes getUANodeViaId(int nodeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getUANodesPath", ReplyAction="http://tempuri.org/IChqUASettings/getUANodesPathResponse")]
        string[] getUANodesPath(CHQ.RD.WebServiceListener.UASV.UANodes[] nodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/saveSubscription", ReplyAction="http://tempuri.org/IChqUASettings/saveSubscriptionResponse")]
        int saveSubscription(CHQ.RD.WebServiceListener.UASV.UASubScription header, CHQ.RD.WebServiceListener.UASV.UASubDetail detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/removeSubscription", ReplyAction="http://tempuri.org/IChqUASettings/removeSubscriptionResponse")]
        int removeSubscription(string subname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/addSubscription", ReplyAction="http://tempuri.org/IChqUASettings/addSubscriptionResponse")]
        int addSubscription(CHQ.RD.WebServiceListener.UASV.UASubScription header);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/saveSubscriptionHeader", ReplyAction="http://tempuri.org/IChqUASettings/saveSubscriptionHeaderResponse")]
        int saveSubscriptionHeader(CHQ.RD.WebServiceListener.UASV.UASubScription header);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/addSubdetails", ReplyAction="http://tempuri.org/IChqUASettings/addSubdetailsResponse")]
        int addSubdetails(string subname, string[] nodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/removeSubdetails", ReplyAction="http://tempuri.org/IChqUASettings/removeSubdetailsResponse")]
        int removeSubdetails(string subname, string[] nodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubscriptions", ReplyAction="http://tempuri.org/IChqUASettings/getSubscriptionsResponse")]
        CHQ.RD.WebServiceListener.UASV.UASubScription[] getSubscriptions(string pname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubdetails", ReplyAction="http://tempuri.org/IChqUASettings/getSubdetailsResponse")]
        CHQ.RD.WebServiceListener.UASV.UANodes[] getSubdetails(string subname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubDetailsViaId", ReplyAction="http://tempuri.org/IChqUASettings/getSubDetailsViaIdResponse")]
        CHQ.RD.WebServiceListener.UASV.UANodes[] getSubDetailsViaId(int subid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/moveSubscriptions", ReplyAction="http://tempuri.org/IChqUASettings/moveSubscriptionsResponse")]
        int moveSubscriptions(string subname, string targetsubname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubscription", ReplyAction="http://tempuri.org/IChqUASettings/getSubscriptionResponse")]
        CHQ.RD.WebServiceListener.UASV.UASubScription getSubscription(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubscriptionViaId", ReplyAction="http://tempuri.org/IChqUASettings/getSubscriptionViaIdResponse")]
        CHQ.RD.WebServiceListener.UASV.UASubScription getSubscriptionViaId(int subid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/saveDataBatchSettings", ReplyAction="http://tempuri.org/IChqUASettings/saveDataBatchSettingsResponse")]
        int saveDataBatchSettings(CHQ.RD.WebServiceListener.UASV.UADatabatchSetting batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/delDataBatchSettings", ReplyAction="http://tempuri.org/IChqUASettings/delDataBatchSettingsResponse")]
        int delDataBatchSettings(int batchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getDatabatchSetting", ReplyAction="http://tempuri.org/IChqUASettings/getDatabatchSettingResponse")]
        CHQ.RD.WebServiceListener.UASV.UADatabatchSetting getDatabatchSetting(int batchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getAllDatabatchSettings", ReplyAction="http://tempuri.org/IChqUASettings/getAllDatabatchSettingsResponse")]
        CHQ.RD.WebServiceListener.UASV.UADatabatchSetting[] getAllDatabatchSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getDatabatchNodes", ReplyAction="http://tempuri.org/IChqUASettings/getDatabatchNodesResponse")]
        CHQ.RD.WebServiceListener.UASV.UANodes[] getDatabatchNodes(int batchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getConnectionString", ReplyAction="http://tempuri.org/IChqUASettings/getConnectionStringResponse")]
        string getConnectionString(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/checkDBPrepare", ReplyAction="http://tempuri.org/IChqUASettings/checkDBPrepareResponse")]
        int checkDBPrepare(int batchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/createDBPrepare", ReplyAction="http://tempuri.org/IChqUASettings/createDBPrepareResponse")]
        int createDBPrepare(int batchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getDataTransactSql", ReplyAction="http://tempuri.org/IChqUASettings/getDataTransactSqlResponse")]
        string getDataTransactSql(int batchid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/tranRealdata", ReplyAction="http://tempuri.org/IChqUASettings/tranRealdataResponse")]
        void tranRealdata(System.Collections.Generic.Dictionary<string, object> value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getScalar", ReplyAction="http://tempuri.org/IChqUASettings/getScalarResponse")]
        string getScalar(string TableName, string Keycolumn, string keyValue, string TargetColumn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/saveAlertType", ReplyAction="http://tempuri.org/IChqUASettings/saveAlertTypeResponse")]
        int saveAlertType(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getAlertTypes", ReplyAction="http://tempuri.org/IChqUASettings/getAlertTypesResponse")]
        CHQ.RD.WebServiceListener.UASV.UAAlertType[] getAlertTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getAlertType", ReplyAction="http://tempuri.org/IChqUASettings/getAlertTypeResponse")]
        CHQ.RD.WebServiceListener.UASV.UAAlertType getAlertType(int alertTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSysAlertData", ReplyAction="http://tempuri.org/IChqUASettings/getSysAlertDataResponse")]
        System.Data.DataTable getSysAlertData(int subviewid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/saveAlert", ReplyAction="http://tempuri.org/IChqUASettings/saveAlertResponse")]
        int saveAlert(System.Data.DataTable dt, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/saveNewSubView", ReplyAction="http://tempuri.org/IChqUASettings/saveNewSubViewResponse")]
        int saveNewSubView(CHQ.RD.WebServiceListener.UASV.UASubView header, CHQ.RD.WebServiceListener.UASV.UASubViewItem[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/saveEditedSubview", ReplyAction="http://tempuri.org/IChqUASettings/saveEditedSubviewResponse")]
        int saveEditedSubview(CHQ.RD.WebServiceListener.UASV.UASubView header, CHQ.RD.WebServiceListener.UASV.UASubViewItem[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubviewList", ReplyAction="http://tempuri.org/IChqUASettings/getSubviewListResponse")]
        CHQ.RD.WebServiceListener.UASV.UASubView[] getSubviewList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubviewItems", ReplyAction="http://tempuri.org/IChqUASettings/getSubviewItemsResponse")]
        CHQ.RD.WebServiceListener.UASV.UASubViewItem[] getSubviewItems(int subviewid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubviewData", ReplyAction="http://tempuri.org/IChqUASettings/getSubviewDataResponse")]
        System.Collections.Generic.Dictionary<int, object> getSubviewData(int subviewid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubviewDataAsTable", ReplyAction="http://tempuri.org/IChqUASettings/getSubviewDataAsTableResponse")]
        System.Data.DataTable getSubviewDataAsTable(int subviewid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getSubviewItemsRTData", ReplyAction="http://tempuri.org/IChqUASettings/getSubviewItemsRTDataResponse")]
        decimal[] getSubviewItemsRTData(int[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getDomainUserId", ReplyAction="http://tempuri.org/IChqUASettings/getDomainUserIdResponse")]
        int getDomainUserId(string windowsname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getGasFlow", ReplyAction="http://tempuri.org/IChqUASettings/getGasFlowResponse")]
        System.Data.DataTable getGasFlow(System.DateTime begindate, System.DateTime enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getGasATFlow", ReplyAction="http://tempuri.org/IChqUASettings/getGasATFlowResponse")]
        System.Data.DataTable getGasATFlow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getGasHourFlow", ReplyAction="http://tempuri.org/IChqUASettings/getGasHourFlowResponse")]
        System.Data.DataTable getGasHourFlow(System.DateTime begindate, System.DateTime enddate, int caluanodeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/Get_QCAnalyse_P", ReplyAction="http://tempuri.org/IChqUASettings/Get_QCAnalyse_PResponse")]
        System.Data.DataTable Get_QCAnalyse_P(System.DateTime begindate, System.DateTime endDate, int includeJL, int sampleNo, int zlh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/Get_QcAnalyse_Item_P", ReplyAction="http://tempuri.org/IChqUASettings/Get_QcAnalyse_Item_PResponse")]
        string Get_QcAnalyse_Item_P(System.DateTime begindate, System.DateTime endDate, int includeJL, int sampleNo, int zlh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/Get_QcAnylyse_PAl", ReplyAction="http://tempuri.org/IChqUASettings/Get_QcAnylyse_PAlResponse")]
        System.Data.DataTable Get_QcAnylyse_PAl(System.DateTime begindate, System.DateTime enddate, int zlh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/Get_QcAnylyse_CMn", ReplyAction="http://tempuri.org/IChqUASettings/Get_QcAnylyse_CMnResponse")]
        System.Data.DataTable Get_QcAnylyse_CMn(System.DateTime begindate, System.DateTime enddate, int zlh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getLtWave01", ReplyAction="http://tempuri.org/IChqUASettings/getLtWave01Response")]
        string getLtWave01();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChqUASettings/getLtWave01Hist", ReplyAction="http://tempuri.org/IChqUASettings/getLtWave01HistResponse")]
        string getLtWave01Hist(System.DateTime begindate, System.DateTime enddate, bool recent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChqUASettingsChannel : CHQ.RD.WebServiceListener.UASV.IChqUASettings, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChqUASettingsClient : System.ServiceModel.ClientBase<CHQ.RD.WebServiceListener.UASV.IChqUASettings>, CHQ.RD.WebServiceListener.UASV.IChqUASettings {
        
        public ChqUASettingsClient() {
        }
        
        public ChqUASettingsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChqUASettingsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChqUASettingsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChqUASettingsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public CHQ.RD.WebServiceListener.UASV.CompositeType GetDataUsingDataContract(CHQ.RD.WebServiceListener.UASV.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public int saveUANodes(CHQ.RD.WebServiceListener.UASV.UANodes node) {
            return base.Channel.saveUANodes(node);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UANodes[] getUANodes(string parent) {
            return base.Channel.getUANodes(parent);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UANodes getUANode(string name) {
            return base.Channel.getUANode(name);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UANodes getUANodeViaId(int nodeid) {
            return base.Channel.getUANodeViaId(nodeid);
        }
        
        public string[] getUANodesPath(CHQ.RD.WebServiceListener.UASV.UANodes[] nodes) {
            return base.Channel.getUANodesPath(nodes);
        }
        
        public int saveSubscription(CHQ.RD.WebServiceListener.UASV.UASubScription header, CHQ.RD.WebServiceListener.UASV.UASubDetail detail) {
            return base.Channel.saveSubscription(header, detail);
        }
        
        public int removeSubscription(string subname) {
            return base.Channel.removeSubscription(subname);
        }
        
        public int addSubscription(CHQ.RD.WebServiceListener.UASV.UASubScription header) {
            return base.Channel.addSubscription(header);
        }
        
        public int saveSubscriptionHeader(CHQ.RD.WebServiceListener.UASV.UASubScription header) {
            return base.Channel.saveSubscriptionHeader(header);
        }
        
        public int addSubdetails(string subname, string[] nodes) {
            return base.Channel.addSubdetails(subname, nodes);
        }
        
        public int removeSubdetails(string subname, string[] nodes) {
            return base.Channel.removeSubdetails(subname, nodes);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UASubScription[] getSubscriptions(string pname) {
            return base.Channel.getSubscriptions(pname);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UANodes[] getSubdetails(string subname) {
            return base.Channel.getSubdetails(subname);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UANodes[] getSubDetailsViaId(int subid) {
            return base.Channel.getSubDetailsViaId(subid);
        }
        
        public int moveSubscriptions(string subname, string targetsubname) {
            return base.Channel.moveSubscriptions(subname, targetsubname);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UASubScription getSubscription(string name) {
            return base.Channel.getSubscription(name);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UASubScription getSubscriptionViaId(int subid) {
            return base.Channel.getSubscriptionViaId(subid);
        }
        
        public int saveDataBatchSettings(CHQ.RD.WebServiceListener.UASV.UADatabatchSetting batch) {
            return base.Channel.saveDataBatchSettings(batch);
        }
        
        public int delDataBatchSettings(int batchId) {
            return base.Channel.delDataBatchSettings(batchId);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UADatabatchSetting getDatabatchSetting(int batchid) {
            return base.Channel.getDatabatchSetting(batchid);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UADatabatchSetting[] getAllDatabatchSettings() {
            return base.Channel.getAllDatabatchSettings();
        }
        
        public CHQ.RD.WebServiceListener.UASV.UANodes[] getDatabatchNodes(int batchid) {
            return base.Channel.getDatabatchNodes(batchid);
        }
        
        public string getConnectionString(string type) {
            return base.Channel.getConnectionString(type);
        }
        
        public int checkDBPrepare(int batchid) {
            return base.Channel.checkDBPrepare(batchid);
        }
        
        public int createDBPrepare(int batchid) {
            return base.Channel.createDBPrepare(batchid);
        }
        
        public string getDataTransactSql(int batchid) {
            return base.Channel.getDataTransactSql(batchid);
        }
        
        public void tranRealdata(System.Collections.Generic.Dictionary<string, object> value) {
            base.Channel.tranRealdata(value);
        }
        
        public string getScalar(string TableName, string Keycolumn, string keyValue, string TargetColumn) {
            return base.Channel.getScalar(TableName, Keycolumn, keyValue, TargetColumn);
        }
        
        public int saveAlertType(System.Data.DataTable dt) {
            return base.Channel.saveAlertType(dt);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UAAlertType[] getAlertTypes() {
            return base.Channel.getAlertTypes();
        }
        
        public CHQ.RD.WebServiceListener.UASV.UAAlertType getAlertType(int alertTypeId) {
            return base.Channel.getAlertType(alertTypeId);
        }
        
        public System.Data.DataTable getSysAlertData(int subviewid) {
            return base.Channel.getSysAlertData(subviewid);
        }
        
        public int saveAlert(System.Data.DataTable dt, int userId) {
            return base.Channel.saveAlert(dt, userId);
        }
        
        public int saveNewSubView(CHQ.RD.WebServiceListener.UASV.UASubView header, CHQ.RD.WebServiceListener.UASV.UASubViewItem[] items) {
            return base.Channel.saveNewSubView(header, items);
        }
        
        public int saveEditedSubview(CHQ.RD.WebServiceListener.UASV.UASubView header, CHQ.RD.WebServiceListener.UASV.UASubViewItem[] items) {
            return base.Channel.saveEditedSubview(header, items);
        }
        
        public CHQ.RD.WebServiceListener.UASV.UASubView[] getSubviewList() {
            return base.Channel.getSubviewList();
        }
        
        public CHQ.RD.WebServiceListener.UASV.UASubViewItem[] getSubviewItems(int subviewid) {
            return base.Channel.getSubviewItems(subviewid);
        }
        
        public System.Collections.Generic.Dictionary<int, object> getSubviewData(int subviewid) {
            return base.Channel.getSubviewData(subviewid);
        }
        
        public System.Data.DataTable getSubviewDataAsTable(int subviewid) {
            return base.Channel.getSubviewDataAsTable(subviewid);
        }
        
        public decimal[] getSubviewItemsRTData(int[] items) {
            return base.Channel.getSubviewItemsRTData(items);
        }
        
        public int getDomainUserId(string windowsname) {
            return base.Channel.getDomainUserId(windowsname);
        }
        
        public System.Data.DataTable getGasFlow(System.DateTime begindate, System.DateTime enddate) {
            return base.Channel.getGasFlow(begindate, enddate);
        }
        
        public System.Data.DataTable getGasATFlow() {
            return base.Channel.getGasATFlow();
        }
        
        public System.Data.DataTable getGasHourFlow(System.DateTime begindate, System.DateTime enddate, int caluanodeid) {
            return base.Channel.getGasHourFlow(begindate, enddate, caluanodeid);
        }
        
        public System.Data.DataTable Get_QCAnalyse_P(System.DateTime begindate, System.DateTime endDate, int includeJL, int sampleNo, int zlh) {
            return base.Channel.Get_QCAnalyse_P(begindate, endDate, includeJL, sampleNo, zlh);
        }
        
        public string Get_QcAnalyse_Item_P(System.DateTime begindate, System.DateTime endDate, int includeJL, int sampleNo, int zlh) {
            return base.Channel.Get_QcAnalyse_Item_P(begindate, endDate, includeJL, sampleNo, zlh);
        }
        
        public System.Data.DataTable Get_QcAnylyse_PAl(System.DateTime begindate, System.DateTime enddate, int zlh) {
            return base.Channel.Get_QcAnylyse_PAl(begindate, enddate, zlh);
        }
        
        public System.Data.DataTable Get_QcAnylyse_CMn(System.DateTime begindate, System.DateTime enddate, int zlh) {
            return base.Channel.Get_QcAnylyse_CMn(begindate, enddate, zlh);
        }
        
        public string getLtWave01() {
            return base.Channel.getLtWave01();
        }
        
        public string getLtWave01Hist(System.DateTime begindate, System.DateTime enddate, bool recent) {
            return base.Channel.getLtWave01Hist(begindate, enddate, recent);
        }
    }
}
